version: '2.2'

services:
  app:
    build: .
    image: stroke_analysis:latest  # ğŸ‘ˆ åŠ é€™è¡Œ
    volumes:
      - .:/app
    working_dir: /app
    command: python run_experiments.py  # ä½ ä¹Ÿå¯ä»¥æ”¹æˆä½ è¦åŸ·è¡Œçš„æª”å
